### ISSUE TITLE
Compass not working on Galaxy S3/LineageOS 14.1

### ISSUE THREAD

**Issue by breversa** [mvglasow/satstat#122]
Hi,

I recently refurbished a Samsung Galaxy S III (GT-I9300) with LineageOS 14.1 (previous ROM was stock) before giving it to a friend.

However, SatStat (F-Droid v3.2 2017-06-23) doesn't show any compass orientation : the north arrow stays frozen to the 12 o'clock position.

I first thought that the GT-I9300 had no magnetic compass (odd, but why not ?), but other apps such as GPS Status & Toolbox report magnetic orientation just fine, so I believe it's a SatStat issue.

Please note that not having my hands on the device anymore, I'll need a bit more time to have my friend test and report back. :-)

I'll have him check the sensors page (cf https://github.com/mvglasow/satstat/issues/37), and have a look at the logcat too.

**Comment by breversa** [comment]
Sensor page :
![signal-2017-07-12-172245](https://user-images.githubusercontent.com/2071276/28127821-1085ccf6-672e-11e7-8e63-1b66d95f9f0d.png)

**Comment by mvglasow** [comment]
This is odd... I develop on LineageOS (currently 14.1) and it generally works for me. I also see that the magnetometer reports something, so that can be ruled out as well.

I have, however, noticed that sometimes sensors stop reporting values. In some cases, rotating the device a few times around each axis has helped; in other cases only a reboot would fix things. Have you/your friend tried this? Have the other apps been tried immediately after observing the issue with SatStat? If there was some time between the different tests, temporary hiccups in the OS might affect one app but not the other.

SatStat just registers to receive sensor updates and updates the screen as new sensors are reported, thus there is little which can go wrong on that side—especially affecting just one sensor but not others, as the logic is the same for all.

**Comment by breversa** [comment]
Thanks for your quick reply. :-)

I'm pretty sure I tried to "reset" the compass by waving the device in the 8-move fashion, and that did not change a thing. The device has also been rebooted between test (though not FOR the tests), to no avail.

Would a logcat be of any help ?

**Comment by breversa** [comment]
Apparently, if one starts GPS Status & Toolbox THEN Satstat, magnetic orientation DOES work… but the north needle seems *very* slow to point to the right direction. Waving the phone in 8-pattern helps almost not.

Weird thing is, in GPS S&T, the north needle points immediately to the right direction.

I believe it's because SatStat reads the orientation sensor only to point the north, while GPS S&T might use the magnetometer too ?

**Comment by barbeau** [comment]
I'm guessing that GPS S&T probably uses the [`TYPE_ROTATION_VECTOR` sensor](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ROTATION_VECTOR), which fuses multiple sensors for orientation.  From a quick scan it looks like SatSat uses the [`TYPE_ORIENTATION`](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ORIENTATION) sensor.  For details see https://stackoverflow.com/a/36454090/937715.

You could try [GPSTest](https://github.com/barbeau/gpstest) as well as another reference point - it uses the `TYPE_ROTATION_VECTOR` fused sensor.

**Comment by mvglasow** [comment]
That is indeed possible. SatStat relies on the orientation sensor—it outputs sensor data, including all their ugliness, as being able to detect that ugliness is one of the main purposes of SatStat. I’d be interested to learn what GPSTest reports, though.

**Comment by breversa** [comment]
I'll have my friend give it a go when he gets back home next month.

**Comment by oliver** [comment]
Same problem here, with an S4 Mini (GT-I9195) with LineageOS 14.1 and SatStat 3.2 (git-da69945) from F-Droid.

SatStat nearly always has north pointing up, even when I turn the phone around. In some rare cases (when the displays changes from portrait to landscape or back) SatStat suddenly shows the correct compass orientation, but even then the needle doesn't move when I move the phone.

GPS Test 2.1.10 shows (mostly) correct compass direction, and same in OsmAnd and other compass apps. It's only "mostly" correct in that it still deviates from actual north by several degree, but that's probably more a calibration issue. In all of these apps the needle immediately moves when I move the phone.

**Comment by mvglasow** [comment]
There’s another method to get compass orientation, based on the device rotation vector, which indeed seems to give better (i.e. more precise) results than the orientation sensor. I can try and implement the orientation for the GPS this way.

**Comment by mvglasow** [comment]
d7d2ee1d implements a fallback to orientation based on the rotation matrix.

I now know of three ways to get device yaw (compass bearing):
* from the `TYPE_ORIENTATION` sensor, long deprecated but still works on many devices
* from the `TYPE_ACCELEROMETER` and `TYPE_MAGNETIC_FIELD` sensors, by processing their  readings into a rotation matrix and obtaining a bearing from that
* based on the `TYPE_ROTATION_VECTOR` sensor, by processing it into a rotation matrix and obtaining a bearing from that

The last two methods seem to give mostly the same results but are even more error-prone than `TYPE_ORIENTATION`. I therefore set a flag as soon as I get a nonzero bearing from `TYPE_ORIENTATION`: if the flag is set, I take bearing directly from the sensor; else I calculate it from `TYPE_ACCELEROMETER` and `TYPE_MAGNETIC_FIELD` readings.

If someone feels like building the current version, I’d be happy to hear your feedback. Otherwise it’ll go into the next official build as is.

**Comment by barbeau** [comment]
@mvglasow Just curious - which devices did you test on that showed `TYPE_ROTATION_VECTOR` to be inferior to `TYPE_ORIENTATION`?  And in what way was the data worse (e.g., drift, jitter)?

**Comment by mvglasow** [comment]
@barbeau Glad to see you here, would love to hear your advice on this. The device I tested on is a OnePlus One running LineageOS 14.1. Issues I encountered:

* Bearing is less stable—with the device lying flat on the table, `TYPE_ORIENTATION` is pretty much stationary, whereas with the other two methods, the arrow will oscillate back and forth.
* If the compass has recently been calibrated (by rotating the device around each axis three times), `TYPE_ORIENTATION` gives a fairly accurate bearing, whereas the other two are still considerably off.
* When I move the device into the upright position and rotate it a bit further, the arrow suddenly flips into the opposite direction. This happens even if the Y axis of the device originally pointed west.

In a different app, I have calculated bearing using the rotation matrix, but passed sensor data through a lowpass filter before using it to calculate the rotation matrix, and results were superior to the orientation sensor—stable and more accurate.

**Comment by barbeau** [comment]
@mvglasow I'd be very hesitant on prioritizing `TYPE_ORIENTATION` over `TYPE_ROTATION_VECTOR` based on single device performance.  `TYPE_ORIENTATION` was deprecated because the exact behavior wasn't well-specified in the Android docs, so OEMs implemented it several different ways that weren't compatible with one another - there was significant fragmentation.  This gets especially sketching when handling device orientation changes (portrait to landscape), and considering that some Android devices (tablets) specify landscape as the default orientation.  The `TYPE_ROTATION_VECTOR` should go through more CTS test than `TYPE_ORIENTATION` before an OEM launches a device.

I just grabbed the `master` branch and fired it up on my LG G5 w/ stock Android 7.0 and I have *very* low frame rate when spinning the device on it's axis when flat, on the order of under 5 fps - here's a screen capture:
https://www.dropbox.com/s/cvn6gxoxlwgu0qc/satstat-LG-G5-TYPE_ORIENTATION.mp4?dl=0

I would going to compare this against rotation vector version, but from a quick look through the code, though, I don't see `TYPE_ROTATION_VECTOR` being registered anywhere?  

Standard practice I've seen is to register this sensor, listen for that specific type, and then use `SensorManager.getRotationMatrixFromVector()` to get the rotation matrix.  See example in GPSTest at https://github.com/barbeau/gpstest/blob/master/GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java#L847.

**Comment by barbeau** [comment]
So, I think the fps issue is actually a bug in the hard-coded sensor rate?  I opened a PR at https://github.com/mvglasow/satstat/pull/129 - please take a look and let me know what you think.

**Comment by mvglasow** [comment]
@barbeau Thanks for digging into this! Re `TYPE_ROTATION_VECTOR`, I tried this only once but never committed it, hence no traces of it in the repo. The sensor would be registered in `MainActivity` with the others and processed in `GpsSectionFragment`. Instead of calculating the rotation matrix from gyroscope and acceleration, I calculated it from the rotation vector using `SensorManager.getRotationMatrixFromVector()`, then processed the rotation matrix the same way I do now.

I’ll merge your PR and see what happens.

**Comment by mvglasow** [comment]
After merging #129, I commented out the code for `TYPE_ORIENTATION_SENSOR` so the rotation matrix would be used for bearing. Response is quicker but the issues are the same. In the sample below, I gently moved the device around its Z axis, then lifted it up (rotating it by its Y axis by slightly over 90 degrees) and put it down again.

[ScreenRecord-2017-09-23-23-39-27.mp4.zip](https://github.com/mvglasow/satstat/files/1326894/ScreenRecord-2017-09-23-23-39-27.mp4.zip)

**Comment by barbeau** [comment]
@mvglasow thanks - do you see the same behavior if you install GPSTest and switch to "Sky" tab (far right)?

https://github.com/barbeau/gpstest/releases/download/v2.1.11/GPSTest-v2.1.11.apk

**Comment by mvglasow** [comment]
The sky plot in GPS Test doesn’t “tremble” the way the one in SatStat does. However, when I lift the device off the table, rotating it around its X axis by slightly over 90 degrees, the compass suddenly flips around.

Another thing I notice, in the link to the GPSTest code you posted above, you appear to process data from both TYPE_ORIENTATION and TYPE_ROTATION_VECTOR sensors (assuming both are registered)—thus I’m wondering if I’m seeing a mix of data from two different sensors here.

**Comment by barbeau** [comment]
The sudden compass flip is expected behavior, or at least that's been consistent on every device I've tested on for most compass apps.  I've never really looked into how to correct this, but I'm assuming you could probably just invert the values.

In GPSTest I register only the one of the two sensors - any platform that supports the `TYPE_ROTATION_VECTOR` uses it, otherwise the `TYPE_ORIENTATION` is used:

~~~
    private void addOrientationSensorListener() {
        if (GpsTestUtil.isRotationVectorSensorSupported(this)) {
            // Use the modern rotation vector sensors
            Sensor vectorSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);
            mSensorManager.registerListener(this, vectorSensor, 16000); // ~60hz
        } else {
            // Use the legacy orientation sensors
            Sensor sensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ORIENTATION);
            if (sensor != null) {
                mSensorManager.registerListener(this, sensor,
                        SensorManager.SENSOR_DELAY_GAME);
            }
        }
    }

    public static boolean isRotationVectorSensorSupported(Context context) {
        SensorManager sensorManager = (SensorManager) context
                .getSystemService(Context.SENSOR_SERVICE);
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.GINGERBREAD &&
                sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR) != null;
    }
~~~

I think you're right - if you're getting callbacks from multiple sensors and using every callback to re-draw it may be overly re-drawing the compass, which would result in the "tremble".

**Comment by mvglasow** [comment]
I’ve just tagged release 3.3, which should become available on F-Droid in the next few days. Can you please test and let me know if that resolves the original issue?

**Comment by breversa** [comment]
It built fine this morning (https://f-droid.org/wiki/index.php?title=com.vonglasow.michael.satstat/lastbuild_3030&redirect=no) so I should be able to test shortly. :-)

**Comment by breversa** [comment]
I confirm that the current version works fine on Galaxy S3/LineageOS 14.1
Sorry for the late test.

**Comment by mvglasow** [comment]
Great—thanks for letting me know!
