### ISSUE TITLE
crash on opening downloadpath

### ISSUE THREAD

**Issue by Rubylion** [mvglasow/satstat#154]
Hi. when I try to set the downloadfolder Satstat always crashes.
The browser app complains about a null pointer exception

here's the debug

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mixplorer/com.mixplorer.activities.BrowseActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mixplorer.e.ae$a.ordinal()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mixplorer.e.ae$a.ordinal()' on a null object reference
	at com.mixplorer.e.ae.a(Unknown Source)
	at com.mixplorer.e.ae.b(Unknown Source)
	at com.mixplorer.e.ae.a(Unknown Source)
	at com.mixplorer.e.ae.b(Unknown Source)
	at com.mixplorer.e.g.h(Unknown Source)
	at com.mixplorer.activities.BrowseActivity.a(Unknown Source)
	at com.mixplorer.activities.BrowseActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 10 more
-

**Comment by mvglasow** [comment]
This looks like a bug in your file manager app—this is where the NPE is thrown (`Attempt to invoke virtual method 'int com.mixplorer.e.ae$a.ordinal()' on a null object reference at com.mixplorer.e.ae.a`), and I don’t see any SatStat classes in the stack trace at all. The file manager gets invoked through an Intent, and it works for me with a fork of CM FIle Manager (available on F-Droid).

**Comment by Rubylion** [comment]
thanx. i'll check it

**Comment by Rubylion** [comment]
About the filemanager… You're right that the manager crashes, everytime I try to set the path in satstat. But I don't understand, why the integrated android file manager doesn't open instead.
I haven't set the 'Mixplorer' as default or whatever.
I'm on LineageOs 14.1
Could you check that?
Regards

**Comment by mvglasow** [comment]
The issue is that Android, for all I know, lacks a standard way to tell the system “open this folder in a file manager”. In fact, Android lacked a file manager for a long time, which is why numerous third-party file managers emerged. Each came up with its own, proprietary intent or URL format. Below is what SatStat currently supports:

		{ Intent.ACTION_PICK, "folder://" },                      // CM File Manager, Blackmoon File Browser, possibly others
		{ "org.openintents.action.PICK_DIRECTORY", "file://" },   // OI File Manager, possibly others
		{ "com.estrongs.action.PICK_DIRECTORY", "file://" },      // ES File Explorer
		{ "com.androidworkz.action.PICK_DIRECTORY", "file://" }

All of these are tried in the order shown here, until an app is found that handles that particular intent.

Because the usual default app mechanisms work based on intents, they do not work as expected here. The order of intents SatStat tries effectively imposes a hard-coded priority. The app chooser presumably would only get displayed if two or more apps supported the same intent, and there were no apps supporting any intent higher up in the list.

In your case, Mixplorer is probably the first app which handles any of the intents in the list, and the only one handling that particular intent (whichever that is).

I assume `com.mixplorer` is a third-party APK, as I don’t find it anywhere on my device (running LineageOS 15.1). I suggest you address this issue to the authors of Mixplorer (what presumably caused the crash is that it was called to open a nonexistent folder, or with an empty URL).

As for why I don’t use the built-in file manager: apart from the UI not being available in earlier Android versions, the default UI also doesn’t support file URLs. There’s no easy way to translate the user’s choice from that UI into a local file path (which is what Mapsforge needs). Even if I got it to work on the current version of Android, the next version could easily break it, because it relies on undocumented functionality that is not guaranteed to remain stable.

**Comment by Rubylion** [comment]
all right.  So you mean that android storage manager is not compatible over the different android versions?
I will ask the mixplorer team though. thank you

**Comment by mvglasow** [comment]
Storage Manager works with its own URIs rather than file paths. The upside is that, as long as the app uses Android Storage Framework, this allows transparent access to local resources as well as cloud resources, without requiring apps to worry about the differences. The downside is that any component that works with files needs to use Android Storage Framework, which is a bummer for portability, as simple file paths are not supported. The latter are, however, what Mapsforge expects (which is being used for map display).
