### ISSUE TITLE
offline maps storage /sdcard/org.mapsforge

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mvglasow/satstat#167]
1. storage permission is required for this 
2. it's left after application purge

If the internal storage is not the proper place for these files there is an an /sdcard/Android/ folder. It doesn't require storage permission, accessible by user, and will be removed after application removal.

**Comment by mvglasow** [comment]
This is in fact by design, as it allows maps to be shared between multiple apps. Also, data getting deleted when the app installed I see as a bug rather than a feature (why would I want to delete my photos if I uninstall the camera app?), or ulterior motives on the part of Google (“if it matters to you, store it on servers we control, rather than out of our reach”).

**Comment by c-e-p-x-u-o** [comment]
OK, could you make an option to choose where to store it.

I (and many others) don't like to give satstat access to my photos (storage permission), and don't need this files after app removal. But like use it (see maps) without internet connection.
