### ISSUE TITLE
Disable/grey out "Reload AGPS data" for incompatible devices

### ISSUE THREAD

**Issue by breversa** [mvglasow/satstat#50]
Hi,

It took me a lot of time to understand (after playing with both SatStat and GPS Status & Toolbox) why reloading AGPS data did not properly work with my Samsung Galaxy Nexus (maguro) :
1- Reload AGPS data query is a fire-and-forget action with no control/status update
2- The Galaxy Nexus features a SiRFstar IV GPS chip which (according to this : http://pocketnow.com/hardware-1/sirfstar-iv-to-compete-with-agps-for-fast-acquisition-times) does not use AGPS

My question is twofold :
- can anyone confirm the AGPS incompatibility of the Galaxy Nexus ?
- if so, is there any way to disable/grey out the "Reload AGPS data" for incompatible devices ? It would save a lot of time to people unaware of this fact (like I was) who tried to improve their GPS but could not understand why…

**Comment by mvglasow** [comment]
Hi,

While I don't know the Galaxy Nexus in detail, I do know that its predecessor, the Nexus S, does support AGPS. Since the Galaxy Nexus is the successor and both devices were built by Samsung, I would be somewhat surprised to see this feature being removed.

The trouble is, the Android API has no real support for AGPS. It's supposed to "just work" in the background and apps aren't really supposed to mess with it at all. There is a call to trigger AGPS data download, but that's about it – no information if AGPS is supported and no information if the AGPS update was successful. Some driver implementations do maintain log files (IIRC the Nexus S does), but these are hardware-specific and since SatStat is mostly a one-man show, supporting device-specific features on a wide range of devices is not feasible.

**Comment by breversa** [comment]
I have both the Nexus S and the Galaxy Nexus, so I could test it, but since the API does not help, and you believe it's not worth the effort, it's your call.

Thanks for your quick reply. :-)
