### ISSUE TITLE
Meaning of colors in map view

### ISSUE THREAD

**Issue by breversa** [mvglasow/satstat#53]
Hi,
It would be useful to have a legend of the different colors of dots/circles in map view.

I have guessed that red means satellite (= GPS + GLONASS ?) location, while blue means cell towers and/or (?) wifi location, but it took me a bit of playing around the app.

What's more, there are sometimes grey dot/circle, and I have no idea what they mean.

Maybe show those colors in the "location sources" settings menu ?

**Comment by mvglasow** [comment]
You're right, I should probably document that. 

In a nutshell, each color stands for a location provider. 

Red is GPS, though nowadays most devices also support GLONASS and/or Beidou. Those hybrid chips report all of these systems as extra GPS satellites, thus you get multiple systems under one provider.

Blue is network. Again, Android has a single location provider for both wifi and cell location.

If additional location providers are present on the system (which I have never seen in practice but the Android API allows for it), they will be assigned random colors.

Gray markers are for stale locations, i.e. the last location we got from a provider which is currently not supplying any data. For example, if you enter a tunnel, the GPS marker will turn gray after a few seconds.

BTW, the circle denotes accuracy: smaller circles mean better accuracy. In other words: your actual location is somewhere within the circle.

**Comment by breversa** [comment]
Thank you for confirming what I supposed. :-)

I'm using UnifiedNlp (https://github.com/microg/android_packages_apps_UnifiedNlp) with several (cell/wifi) backends, but as far as I know, they are all "merged" into a single cell+wifi location provider (i.e. blue dot/circle), right ? There's no way to have one dot/circle for each backend to compare them (except (de)activating them so that only one is active at a time) ?

As for the grey markers, how do you tell the GPS stale location from the cell+wifi location (as both can happen at the same time… in the same tunnel, for instance :-P ) ?

**Comment by jkufner** [comment]
@mvglasow This legend should be present directly in the application. Even documentation is too far.

**Comment by breversa** [comment]
For the record, I added the above explanation to https://github.com/mvglasow/satstat/wiki

**Comment by mvglasow** [comment]
I've just implemented a legend, which will be included in the next release.

As for the gray markers – right now you can't tell which stale location is from which provider. I'd expect this to be an issue only in a few rare cases: when you have multiple location providers, several of them have stopped supplying location updates, and you need to know which stale location goes with which provider. I'd expect that to be rare because:

* most devices have no more than 2 location providers (not sure how µG+gapps behave when running side by side, it would be either 2 or 3 providers from an app perspective)
* most use cases would be about analyzing current locations, or when a location goes stale, or verifying if a particular provider is currently supplying a location

If you do have a use case where you need to match a stale location to its provider and cannot infer it from other locations, please let me know.
