### ISSUE TITLE
Shows all connections as GSM

### ISSUE THREAD

**Issue by kroeckx** [mvglasow/satstat#62]
Hi,

I'm wondering if this is an issue with my phone or what the cause is.  In other screenshot I see can show things like "LTE", "CDMA".  For me it's only showing "GSM".  My current connection is using LTE, and the Cell ID is also > 65536, so it can't be GSM.

When I change my settings to only use "GSM only", it will actually show a different LAC and CellID, and even show multiple values.  They all have a grey rectangle in the front, and I wonder if that's normal.  I've seen screenshot with other colors.

If I change to "WCDMA only", it still shows me GSM, with different LAC/Cell ID.

So I wonder why I'm getting that, and if this is somehow related to my phone (Samsung Galaxy S4)

**Comment by mvglasow** [comment]
There are indeed a few bugs in the last released version, which I (hopefully) managed to resolve only these days. I'm currently putting together a new version – once it's out, I'd appreciate your feedback.

The "GSM" section should really be labeled "GSM/UMTS" or "GSM-like" – I have placed them into the same section because the cell ID format is very similar and the Android API also lumps them together in many instances. This is why there's a PSC column in the GSM section (which only makes sense for UMTS).

The next version will also include a legend explaining the meaning of the various colored rectangles. In a nutshell:
* Green: GSM (2G)
* Blue: UMTS
* Purple: LTE
* No rectangle: radio type cannot be determined

Gray rectangles are not defined anywhere in the code. It may be related to #59 (which affects colored squares but IIRC has not been an issue with cell networks). This should also be fixed in the new version – if not, please let me know.

**Comment by mvglasow** [comment]
Version 2.1 has just been committed and should be on F-Droid soon.

**Comment by kroeckx** [comment]
So I just tested the 2.2 version.  It now shows LTE when there is an LTE connection, and GSM when it's GSM.  But it's never showing both at the same time.  Is that expected behaviour, or just something my device does?

It's also always showing a grey icon in front of it, while the legend suggest it should have a color.

**Comment by mvglasow** [comment]
Which and how many cells get displayed indeed differs from device to device. Previous generations of Samsung devices were known to report only one cell (the currently serving one), not sure about the S4. However, also on my OnePlus One I don't see any non-LTE cells when registered with a LTE cell, thus I guess that's somewhat common.

The icons should indeed have a color. I've previously observed rendering issues with certain characters on Marshmallow. What Android version are you running? Do you see colored icons in the Sensors screen?

**Comment by kroeckx** [comment]
It's running the latest available for it, being 5.0.1.

All other places properly show the icon in colour.

**Comment by mvglasow** [comment]
Are you running the stock ROM or a custom one? Can you post a screenshot?

**Comment by kroeckx** [comment]
It's a stock ROM.
