### ISSUE TITLE
support for offline maps

### ISSUE THREAD

**Issue by gdt** [mvglasow/satstat#65]
It would be really nice to have support for offline maps so that 1) the privacy leak would be avoided, 2) data usage would be reduced and 3) they'd work offline and work faster.

It would be further nice if by default at least RadioBeacon and SatStat shared a maps folder, but really it would be nice if all mapsforge-enabled apps looked in some common directory.

**Comment by mvglasow** [comment]
+1 :-)

SatStat already has some of the code for offline maps (rendered locally), albeit commented out. The only thing that's still missing is the config UI to choose the map file to use – which is the main reason SatStat only supports online maps so far. The next release is almost out the door and will mainly be a bug fix/technology update one, but I'm planning on adding that in the release after that. It will be possible to choose that path to the maps, thus sharing maps between apps should work.

I'll also file a feature request for mapsforge about sharing maps (or having a standard way for it), because this isn't just a Radiobeacon/SatStat issue...

**Comment by jkufner** [comment]
Why should Satstat show map at all? We have many other map & navigation applications for this. Satstat should show status of satelites, nothing more.

**Comment by gdt** [comment]
@jkufner: the point is not to show a map, but to show the results of various location providers, specifically GPS and network.  The map is just the background to interpret the location provider results -- it's not a map viewing application.  This is the same reason RadioBeacon has maps (well, that's to show where this session's data was).

**Comment by mvglasow** [comment]
Opened a ticket for shared map paths at https://github.com/mapsforge/mapsforge/issues/832.

It won't make it into the upcoming 2.1 release but I'm planning to add this in a successor release. There are also some dependencies on the mapsforge release schedule: so far SatStat uses mapsforge 0.4.3 with some hacks for features that this version didn't have yet. These have by now been implemented upstream, but the current version 0.6.0 has bugs causing app crashes – some of these will be fixed in the next release, others are still under investigation. Since some APIs regarding offline maps have changed in the meantime, I'd like to migrate to 0.6.0+ before adding offline maps – to avoid doing the same work twice.

@jkufner @gdt A main use case for SatStat is location provider debugging – especially comparing two different location providers (e.g. GPS and Network) and visualizing their accuracies. A map is just the most intuitive way to visualize this. I'm not aware of any other app which does that kind of visualization (multiple location providers and visualization of accuracy).

**Comment by mvglasow** [comment]
I've been working on a few things in the satstat-mapsforge0.6.1 branch over the past few days, with the following results so far:
* Offline maps work. The render theme is the Osmarender-like theme which Radiobeacon users will be familiar with.
* Users can switch between online and offline maps in Settings.
* The path in which SatStat looks for maps is configurable in Settings. If a supported file manager is installed, users can browse the folder structure, else a fallback dialog with a text entry field is shown.
* The fallback dialog for the map path also has buttons to download a supported file manager, using an application manager of your choice.
* SatStat searches the entire map folder and picks the correct map by itself – no need to select a different map when you cross the border. (Subfolders are not searched.)

Still missing: map download directly from the app

Sharing maps with Radiobeacon is possible by configuring the same map folder in both apps. This also works with any other app which allows configuring the map folder.

**Comment by gdt** [comment]
Trying to build the branch fails with

{{{
Error:(58, 17) Failed to resolve: org.mapsforge:mapsforge-map:0.6.1
}}}
Is the gradle config supposed to point to the included jar file?

**Comment by gdt** [comment]
With adding -rc1to the obvious 4 places in the grade file, the branch builds and works.

**Comment by mvglasow** [comment]
Yes, I added that in anticipation of the upcoming release (I use Eclipse and build with Ant, thus I don't use the gradle script myself – I keep it mainly for the F-Droid guys). You should be good just adding `-rc1` – that's the version I currently develop with.

**Comment by gdt** [comment]
I just built
{{{
commit df49c5e161207a28bec98d295ef9af41045e821e
Author: mvglasow <michael -at- vonglasow.com>
Date:   Sun May 29 14:29:43 2016 +0200
}}}
(plus changing to -rc1 in gradle) and the resulting apk seems to run fine, including being able to download an offline map.   The debug messages did seem a bit excessive; presumably you'll turn them down when this is more clearly working ok.

**Comment by mvglasow** [comment]
7e31a73 is finally a feature-complete implementation with support for map download. I've removed the excessive log stuff, and the new code is now merged into the master branch. Mapsforge 0.6.1 is officially out by now, so building with gradle should work as well. If anyone wants to have a go at building and testing – feel free.

**Comment by mvglasow** [comment]
One thing: this is not yet tested for missing permissions (#67) – one needs to grant mass storage permission beforehand (and network access to download maps), else it will most likely crash. Will work on it...

**Comment by mvglasow** [comment]
Mass storage permission is fixed now, SatStat will ask if it's not already granted.

**Comment by mvglasow** [comment]
Version 3.0 with full support for offline maps was published on F-Droid today.

**Comment by jw243** [comment]
I have huge problems since I started experimenting with the offline maps function in satstat 3.1. I specified a folder on my external sd-card for the offline maps. However, it is not possible to download any map. Nothing happens when I select a map for download.
What's more annoying, whenever I tried to download a map, no app on the phone can read the sd-card afterwards. In "storage", the sd-card is then listed as having 0.00B of space available. This happens everytime I tried using the offline map functionality of satstat. 
Is this a serious bug in satstat? Any help would be greatly appreciated.

**Comment by mvglasow** [comment]
@jw243 I've tested this functionality extensively and it works for me.
* What is your Android version?
* Stock or custom ROM (if so, which)?
* Device make and model?
* Did you grant SatStat permission to access storage?
* What is your current setting for the offline map folder? Does the path indeed point to a location on the SD card? (Try tapping the setting – if you have a supported file manager installed, this will bring it up and allow you to browse the folder structure – to rule out that SatStat is trying to access a nonexistent folder.)

**Comment by jw243** [comment]
Thanks for getting back to me. Here are the answers to your questions:
>
>   * What is your Android version?
>
I'm on Android 5.1.1
>
>   * Stock or custom ROM (if so, which)?
>
CyanongenMod 12.1-20160125-UNOFFICIAL-lux. The phone is google-free. I'm 
using the microG framework.
>
>   * Device make and model?
>
Moto X Play Dual Sim - XT1562
>
>   * Did you grant SatStat permission to access storage?
>
How do I do that? So far, every app was able to access the SD-card 
without changing any settings.
>
>   * What is your current setting for the offline map folder? Does the
>     path indeed point to a location on the SD card? (Try tapping the
>     setting – if you have a supported file manager installed, this
>     will bring it up and allow you to browse the folder structure – to
>     rule out that SatStat is trying to access a nonexistent folder.)
>
/storage/sdcard1/Android/data/com.vonglasow.michael.satstat/Karten
This folder exists and it is located on the SD-card.

Thanks for your help. It is greatly appreciated.
Best regards.

**Comment by mvglasow** [comment]
Reading up on storage access permissions, I realize I didn't pay proper attention to your earlier point:

> I specified a folder on my external sd-card for the offline maps.

As I understand [this article](https://possiblemobile.com/2014/03/android-external-storage/), *secondary storage* is no longer writable by apps. That would include SD cards (which I cannot test, as my test devices are a Nexus S and a OnePlus One, neither of which has a SD card slot).

The only workaround I can offer you is to stick with the default path that SatStat offers after installation, which is on primary storage (underneath `getExternalStorageDirectory()`). As I understand it, this will continue to work.

> >   * Did you grant SatStat permission to access storage?
>
> How do I do that? So far, every app was able to access the SD-card without changing any settings.

If you upgraded from an older version of SatStat (2.0 or earlier), you granted this permission on install. On a fresh install of SatStat 3.0 or later, it will prompt you for the permission when they are needed.

> /storage/sdcard1/Android/data/com.vonglasow.michael.satstat/Karten
> This folder exists and it is located on the SD-card.

Did you install SatStat on the SD card or in internal storage? If you installed SatStat on the SD card, then I assume /storage/sdcard1/Android/data/com.vonglasow.michael.satstat would be the app's private data path (which gets deleted upon uninstalling the app), and would be writable by SatStat (but not by any other app).

At the moment, it looks like the bug in SatStat is that it doesn't check the path selected by the user. I'll probably add a check for that, with a warning if the user selects anything that is not underneath `getExternalStorageDirectory()` or `getExternalFilesDir()` and an option to revert to the previous setting.

**Comment by jw243** [comment]
Other apps like Osmand, Camera, etc. can all write to the external 
sd-card without any problem. As far as I know, there are no restrictions 
in Android 5, in Android 6 apps often have problems writing to an 
external sd-card. Apparently, app developers need to program an app 
specifically for Android 6, if they want the app to be able to write to 
external storage. With Android 5, there shouldn't be any problem.

SatStat is installed in internal storage.

It wouldn't bother me, if just SatStat had problems writing to external 
storage. But what really annoys me is, that after trying to download an 
offline map to the external storage, the file system on the sd-card gets 
somehow corrupted in such a way that the phone doesn't recognise the 
sd-card anymore and no app can access the external storage anymore. 
Before, I did not have any problems with the external storage. For 
example, all of my Osmand maps are stored there and I never had problems 
accessing them before. Now, I cannot access them anymore.

I erased the sd-card and downloaded the Osmand maps again. Everything 
worked fine. Then I tried to download SatStat offline map again. And 
again, after that, Osmand could not access the previous downloaded maps 
and the external storage is not recognised anymore by the phone.

How can that happen?


Am 01.08.2016 um 23:46 schrieb mvglasow:
